// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://currnpxszhtsftgztxwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1cnJucHhzemh0c2Z0Z3p0eHd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMjg4NjQsImV4cCI6MjA3MjYwNDg2NH0.oopDiUgZ2W3VkfwJGFRujld5wnwLyIr9419xnZwMddo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});